import os
import shamir  # Imports the shamir.py file you created
from bip_utils import Bip39MnemonicGenerator, Bip39WordsNum, Bip39Languages, Bip39Mnemonic, Bip39MnemonicDecoder

# --- Dependency Mock ---
# The provided shamir.py code depends on a function called 'generate_entropy'.
# We will create a working version of it here using a secure source of randomness.
def generate_entropy(hex=True):
    random_bytes = os.urandom(32)
    if hex:
        return random_bytes.hex()
    return random_bytes

# We must assign our mock function to the shamir module so it can be found.
shamir.generate_entropy = generate_entropy
# --- End of Mock ---


def run_leakage_test():
    """
    Runs a statistical test to prove the word-leaking vulnerability.
    """
    num_trials = 100000
    leak_counter = 0

    print(f"--- Running {num_trials} trials to test for secret leakage ---")

    for i in range(num_trials):
        # 1. Generate a random 12-word secret phrase
        secret_mnemonic_str = Bip39MnemonicGenerator(Bip39Languages.ENGLISH).FromWordsNumber(Bip39WordsNum.WORDS_NUM_12)
        secret_words = set(secret_mnemonic_str.ToList())
        
        # The shamir function requires the secret as raw bytes (entropy)
        secret_bytes = Bip39MnemonicDecoder(Bip39Languages.ENGLISH).Decode(secret_mnemonic_str.ToStr())

        # 2. Split the secret using the flawed logic
        try:
            shares = shamir.split_secret(threshold=3, total=5, secret=secret_bytes)
        except Exception as e:
            print(f"An error occurred during splitting: {e}")
            continue

        # 3. Check for any leaked words in the generated shares
        leak_found_in_trial = False
        for share_index, share_bytes in shares.items():
            try:
                # To check for words, convert the share bytes back to a mnemonic list
                share_words = Bip39MnemonicGenerator(Bip39Languages.ENGLISH).FromEntropy(share_bytes).ToList()
                for word in share_words:
                    if word in secret_words:
                        leak_counter += 1
                        leak_found_in_trial = True
                        break # Found a leak, no need to check other words in this share
            except ValueError:
                # Some generated byte sequences may not be valid entropy for a mnemonic
                continue
            if leak_found_in_trial:
                break # Found a leak, no need to check other shares in this trial
        
        # Progress indicator
        if (i + 1) % 100 == 0:
            print(f"Completed {i + 1}/{num_trials} trials...")

    # 4. Calculate and report the final result
    leak_percentage = (leak_counter / num_trials) * 100
    print("\n--- Test Complete ---")
    print(f"Out of {num_trials} trials, a secret word leak was detected in {leak_counter} trials.")
    print(f"Leak Frequency: {leak_percentage:.2f}%")


if __name__ == "__main__":
    run_leakage_test()